name: Build OCI image

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: hairmare/buildah-action@0.1.1
      with:
        tag: cowsay-hello:latest
